### ISSUE TITLE
Let's add some more docs? A minimal Slack App manifest

### ISSUE THREAD

**Issue by KeesCBakker** [hubot-friends/hubot-slack#18]
Hi, good job on implementing the Bolt API, looks like it works, even with DM's.

It might be a good idea to include the YML for the Slack app. I'm not 100% sure, but it looks like this manifest works in both public channels and direct messages:

```yml
display_information:
  name: Baymax
  description: Personal bot of Kees C. Bakker.
  background_color: "#3d001d"
features:
  app_home:
    home_tab_enabled: false
    messages_tab_enabled: true
    messages_tab_read_only_enabled: false
  bot_user:
    display_name: Baymax
    always_online: true
oauth_config:
  scopes:
    bot:
      - app_mentions:read
      - channels:join
      - channels:history
      - channels:read
      - chat:write
      - im:write
      - im:history
      - im:read
      - users:read
      - groups:history
      - groups:write
      - groups:read
      - mpim:history
      - mpim:write
      - mpim:read
settings:
  event_subscriptions:
    bot_events:
      - app_mention
      - message.channels
      - message.im
      - message.groups
      - message.mpim
  interactivity:
    is_enabled: true
  org_deploy_enabled: false
  socket_mode_enabled: true
  token_rotation_enabled: false
```
